import { StyleSheet } from "react-native";
import { color } from "./baseStyles";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.lightGrey,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  textInput: {
    backgroundColor: color.white,
    width: "100%",
    marginVertical: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderColor: "#aaa",
    borderWidth: 2,
    borderRadius: 5,
  },
  button: {
    width: 300,
    borderRadius: 30,
    marginTop: 20,
    alignSelf: "center",
    padding: 10,
    backgroundColor: color.pink,
  },
  headlineText: {
    fontFamily: "Avenir",
    fontSize: 27,
    fontWeight: "100",
  },
  gradient: {
    flex: 1,
    zIndex: 10,
    flexDirection: "column",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 260,
    borderRadius: 5,
  },
  headline: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    paddingHorizontal: 5,
    paddingBottom: 5,
    marginTop: -20,
    zIndex: 20,
  },
  headlineBio: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    paddingHorizontal: 5,
    paddingBottom: 5,
    zIndex: 20,
    marginTop: -70,
  },
  headlineBioContainer: {
    width: 171,
    height: 50,
  },
  featureImage: {
    flex: 1,
    borderRadius: 5,
    width: "100%",
    height: "100%",
    zIndex: 0,
  },
  articleList: {
    paddingTop: 10,
    width: "100%",
  },
  articleCard: {
    borderRadius: 5,
    marginBottom: 10,
    height: 240,
    width: "100%",
  },
  body: {
    fontSize: 16,
    fontWeight: "normal",
    paddingHorizontal: 20,
    color: color.black,
    lineHeight: 25,
    letterSpacing: 0.1,
    fontFamily: "Arial",
  },
  image: {
    paddingVertical: 20,
    marginVertical: 10,
    alignSelf: "center",
    flexDirection: "row",
    height: 307,
    width: 189,
    padding: 0,
    margin: 0,
  },
  imageList: {
    flexDirection: "row",
  },
  preambel: {
    fontSize: 10,
    fontFamily: "Arial",
    alignSelf: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 5,
  },
  celebrityImage: {
    width: 204,
    height: 204,
    alignSelf: "flex-start",
    borderRadius: 100,
    marginLeft: 10,
  },
  Articlecontainer: {
    flex: 1,
    backgroundColor: color.lightGrey,
    alignItems: "center",
    justifyContent: "center",
    marginTop: -20,
    paddingTop: 30,
    paddingBottom: 10,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  celebrityName: {
    fontFamily: "Arial",
    fontSize: 16,
    paddingTop: 10,
    paddingLeft: 10,
    alignItems: "center",
    fontWeight: "bold",
  },
  bioTitle: {
    fontFamily: "Arial",
    fontWeight: "bold",
    fontSize: 20,
    paddingTop: 20,
    paddingBottom: 20,
    marginVertical: 10,
    paddingHorizontal: 25,
  },
  bioname: {
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: 18,
    paddingTop: 20,
    paddingBottom: 20,
    marginVertical: 10,
    paddingHorizontal: 25,
    alignSelf: "center",
    marginLeft: 30,
  },
  articleListimg: {
    paddingVertical: 20,
    paddingHorizontal: 25,
    marginVertical: 10,
    height: 198,
    width: 180,
    padding: 0,
    marginStart: 10,
    borderRadius: 13,
    alignSelf: "flex-start",
  },
  celebArticleList: {
    marginVertical: 10,
    paddingHorizontal: 25,
    paddingVertical: 20,
    height: 257,
    width: 198,
    borderRadius: 13,
    alignSelf: "flex-start",
  },
});